name: open_lb
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  convert: ^2.1.1
  flutter_swiper: ^1.1.6
  animations: ^1.0.0+5
  http: ^0.12.0+4
  async: ^2.4.0
  english_words: ^3.1.5
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - art.png
    - audio.png
    - biography.png
    - child.png
    - comedy.png
    - detectiv.png
    - fantasy.png
    - history.png
    - medical.png
    - paperbook.png
    - recept.png
    - religion.png
    - romant.png
    - science.png
    - scienceFF.png
    - ads.jpg
    - karate.jpg
    - king.jpg
    - king_L.jpg
    - 1.jpg
    - 2.jpg
    - 3.jpg
    - 4.jpg
    - 5.jpg
    - 6.jpg
    - 1a.jpg
    - 2a.jpg
    - 3a.jpg
    - 4a.jpg
    - 5a.jpg
    - 6a.jpg
    - s7.jpg
    - s4.jpg
    - s1.jpg
    - s2.jpg
    - s3.jpg
    - s5.jpg
    - s6.jpg
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Spartan
       fonts:
         - asset: fonts/Spartan-Regular.ttf
         - asset: fonts/Spartan-Bold.ttf
         - asset: fonts/Spartan-Light.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
